### ISSUE TITLE
No way to load external dependencies

### ISSUE THREAD

**Issue by alexandargyurov** [44lr/sledge#1]
Currently, there is no way to load an external dependency to a mod.

**Example**:
I need to load `Nakama.dll` and `Newtonsoft.Json.dll` as my mod `sledge_TeardownNakama.dll` requires them. Before d0a28d3006df6bb3704884cf739d488d5ff4eca, putting these dependencies in the mods folder worked fine (all though they produced some warnings about not having a config).

After d0a28d3006df6bb3704884cf739d488d5ff4eca, they no longer get loaded due to the refactor done on how mods get loaded. 

**Potential Solution**:
Instead of the `modloader` looking for ALL `.dll` files in the `mods/` folder, we can instead contain each mod in their own seperate subfolder. This way, a mod folder can contain a `dependencies` subfolder, which contains all the `.dll` the mod needs to use to work.

```
|-- mods/
   |-- sledge_TeardownNakama/   <-- mod folder
      |-- dependencies/     <-- dependencies get loaded before we load the main mod
          |-- Nakama.dll
          |-- Newtonsoft.Json.dll
      |-- sledge_TeardownNakama.dll    <-- mod .dll must match mod folder
      |-- sledge_TeardownNakama.info.json
   |-- sledgelib.dll
   |-- sledgelib.runtimeconfig.json
```

Of course, open to other solutions and comments :)

**Comment by 44lr** [comment]
There is actually a function that was supposed to handle mod dependencies [here](https://github.com/44lr/sledge/blob/edcb23f6ac857a8e5d2c085787d6352bac4ab639/source/sledgelib/modloader.cs#L80), but it seems i completely forgot to write **the actual loading part**, oops

I also like your idea for keeping mods and dependencies separate in their respective folders, so, that's definitely being implemented.

Thank you!
